### ISSUE TITLE
Spell Hit bug interacting with Inspiring Presence

### ISSUE THREAD

**Issue by jhonnysmashing** [getov/CharacterStatsTBC#5]
after getting out and in range of shaman, it ends up counting as 2.74% hit (or 34.62 rating) instead of 1%

my test:
unequipped everything = 0 hit rating
enter shaman range = (1%) 12.62 rating
equip gear with 154 rating with shaman in range = 166.62 rating 
leave shaman range = 176 rating ??? (+22 unbuffed hit rating for no reason)
enter shaman range again = 188.62 rating ??? (+12.62 from shaman on top of the bug)

**Comment by getov** [comment]
I managed to reproduce this. There is something wrong with Blizzard's API and I can't find a pattern or way to detect what's going on. It seems to also happen when changing pieces with spell hit, not only the shaman aura.
I am really not sure what I should do in this case.

**Comment by getov** [comment]
It should be fixed in the latest release (1.1.3): https://www.curseforge.com/wow/addons/characterstatstbc-character-stats-tbc/files/3391626
