### ISSUE TITLE
Blessing of Wisdom Mana Regen incorrect

### ISSUE THREAD

**Issue by Jinnai** [getov/CharacterStatsTBC#6]
The tooltip for Mana Regen (While Not Casting) is wrong with Blessing of Wisdom.

Note that the mana regen from Blessing of Wisdom is not affected by casting.

A simple test I did

No gear, no buffs:
CharacterStatsTBC shows
Mana Regen (From Gear): 0
Mana Regen (While Casting): 0
Mana Regen (While Not Casting): 43.2

This means per tick while not casting I get 17.28 mana, confirmed 17-18 by showing power gains combat text.

After buffing Blessing of Wisdom (Rank 7) no talents:
CharacterStatsTBC shows
Mana Regen (From Gear): 0
Mana Regen (While Casting): 41
Mana Regen (While Not Casting): 125.2

Per tick while casting I get 16.4 mana, confirmed 16-17 by showing power gains combat text.
Per tick while not casting I do **not** get 50.08 mana, instead I get 33.68 mana, combat text shows 33-35.

So the correct value for Mana Regen (While Not Casting) would be 84.2 (43.2 + 41).

This matches what the default blizzard tooltip is showing when CharacterStatsTBC is enabled (84).

**Comment by Necrious** [comment]
If this comes up can we look into Mana Shield and Unrelenting Storm in Updating the "out of combat" mana regen stats as well?

Currently level 64 Elemental Shaman:
3/5 Unrelenting Storm (6% Int as mp5) Int: 261 = 15.66 mp5
Mana Shield Buff (43 mp5)
Mana Regen (From Gear):                     4
Mana Regen (While Casting):               4 //Added above should be 62-63, depending on how you want to round.
Mana Regen (While Not Casting): 147.5

**Comment by getov** [comment]
It looks like Blizzard "fixed" their API with some silent update and now they are calculating mp5 from some (maybe all??) auras.
This will get fixed but I expect other things to break. I don't have the ability to test all spells,ta;lnts, classes and gear combinations
