### ISSUE TITLE
Spell hit calculation error (balance druid)

### ISSUE THREAD

**Issue by dyej** [getov/CharacterStatsTBC#7]
I want to add another spell hit calculation error I have noticed. As a balance druid I have 4% (50.4 rating) spell hit from talents. My gear is currently at 159 hit rating (meticulously double and triple checked). This should put me at 209.4 spell hit total (or 16.6%). The addon is reporting 234.69 spell hit rating (18.6%).

This is a concerning bug as raiders rely on carefully hitting hit cap. If anything it should err on the side of caution by reporting a lower number than the real value (possibly missing gems/enchants/talents). Reporting a higher than real hit rating value means there is a calculation error somewhere.

If I am mistaken about anything I would be happy to hear as it means I could replace some of my spell hit gems :D

EDIT: Posting this as a separate issue so that I don't hijack #4 

EDIT 2: I looked through the code that gets spell hit modifiers from class talents, and I'm not sure, but I believe the Balance of Power calculation may be multiplying the 2% per rank by 3 ranks for a total of 6% hit from talents (the talent only has 2 ranks). This would explain the addon reporting that I am exactly 2% higher than my real total spell hit value.

The line is here: https://github.com/getov/CharacterStatsTBC/blob/1847e8236ba60425a1d7d1e92e6ff3c52be3f0bf/CharacterStatsTbcUtils.lua#L37

**Comment by getov** [comment]
Thanks for the report!
I looked through it and I am totally getting the wrong talent. I might be able to push an update tonight

**Comment by dyej** [comment]
Awesome. Thanks for the quick response. Boomkins rejoice!
