### ISSUE TITLE
Incorrectly showing hit rating

### ISSUE THREAD

**Issue by matthewhively** [getov/CharacterStatsTBC#8]
I'm not sure where this mysterious 1.54 hit rating is coming from, but I would guess that its from the 1/5 I have in precision.
So the UI correctly shows I have +1% hit, but doesn't correctly attribute it to talents.
![wow_bug](https://user-images.githubusercontent.com/25018092/126911470-9883a3e4-73ee-457b-ba80-5f5fd93703c8.png)

**Comment by getov** [comment]
I am not sure what the problem is?
You have 1% hit from talents. At your level 1% hit = 10 * (playerLevel - 8)/52 = 1.5384 ~ 1.54 hit rating

**Comment by matthewhively** [comment]
*shrug* all I know is it doesn't seem to be consistent with how it works for spell hit.
For spell hit it shows my actual hit rating + talents = total hit %
For spells it doesn't convert hit from talents into the equivalent hit-rating.
So, if this is intended behavior, then... is spell hit bugged the opposite way?

**Comment by getov** [comment]
It does convert to spell hit rating, but there are special cases depending what class you play (it is displayed differently for warlocks and mages)
If you have a specific problem, please open another issue.
